version: "3"
services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
     - ./data:/var/lib/grafana
     - /var/lib/grafana/plugins
    environment:
     - GF_AUTH_ANONYMOUS_ENABLED=true
     - GF_SECURITY_ALLOW_EMBEDDING=true
     - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
    ports:
     - 3000:3000